#!/usr/bin/with-contenv bash
set -x

if [ ! -f "/config/openvpn-config" ]; then
      echo "File \"/config/openvpn-config\" not found. Check/provide env vars for openvpn provider info."
      echo "Stopping openvpn script."
      exit
      else

      exec \
      s6-setuidgid abc /usr/sbin/openvpn \
      ${CONTROL_OPTS} ${OPENVPN_OPTS} \
      --config "${OPENVPN_CONFIG}"
fi



#CONTROL_OPTS="--script-security 2 --up /etc/openvpn/tunnelUp.sh --down /etc/openvpn/tunnelDown.sh"

